dataset tiny     img size 224
---> ResNet18
loss str Lambda10.0
attack str fat-1-untargeted-10-0.1
saving to ./runs/tiny/fat-1-untargeted-10-0.1_Lambda10.0_e200-b250_sgd-lr0.1-m0.9-wd0.0005_cos
1. Running on rank 0.
Namespace(Lambda=10.0, alpha=0.1, attacker='fat', aug_severity=1, batch_size=250, data_root_path='./data', dataset='tiny', ddp=False, ddp_backend='nccl', decay='cos', decay_epochs=[100, 150], deepaug=False, dist_url='tcp://localhost:23456', epochs=200, gpu='0', lr=0.1, mixture_depth=1, mixture_width=1, model='ResNet18_tiny', momentum=0.9, node_id=0, num_nodes=1, num_workers=16, opt='sgd', resume=False, save_root_path='./runs/', steps=10, targeted=False, tau=1, test_batch_size=1000, wd=0.0005, widen_factor=2)
2. in gpu id == 0
ddp False
3. train batch size 250   num workers 16
4. Tiny data loader
Training images loading from ./data/tiny-224/train
Validation images loading from ./data/tiny-224/val
8. in main fn -> Tiny data len Train 100000   & val 5000
9. Starting dataloader
9. batch size train 250     test 1000
10. data loaders complete
Traceback (most recent call last):
  File "augmax_training_ddp_mnist.py", line 476, in <module>
    train(0, 0)
  File "augmax_training_ddp_mnist.py", line 257, in train
    model = model_fn().to(device)
  File "/home/mt1/21CS60D06/anaconda3/envs/augmax18/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/home/mt1/21CS60D06/anaconda3/envs/augmax18/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/mt1/21CS60D06/anaconda3/envs/augmax18/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/home/mt1/21CS60D06/anaconda3/envs/augmax18/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/mt1/21CS60D06/anaconda3/envs/augmax18/lib/python3.8/site-packages/torch/cuda/__init__.py", line 170, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
